# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'QNRTCKitDemo' do
  pod 'QNRTCKit', '~> 3.1.2'
  pod 'Bugsnag', '5.15.4'
  pod 'PLPlayerKit', '3.4.1'
  pod 'MMMaterialDesignSpinner', '0.2.5'
  pod 'JGProgressHUD', '2.0.3'
  pod 'Masonry', '1.1.0'
  
  pod 'FURenderKit', '~> 8.3.0'
  
  
end
